controllers:
  resource: ../src/Controller/
  type: attribute

app_home:
  path: /
  controller: App\Controller\HomeController::home

app_register:
  path: /register
  controller:
    App\Controller\RegistrationController::register

    #[Route(path: '/login', name: 'app_login')]
app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

app_allChambres:
  path: /chambres
  controller: App\Controller\ChambreController::allChambres

app_chambre:
  path: /chambre
  controller: App\Controller\ChambreController::chambre

app_be_admin:
  path: /passer_admin/{id}
  controller: App\Controller\SecurityController::passerAdmin
  requirements:
    id: '\d+'

app_admin_allChambres:
  path: /admin/chambres
  controller: App\Controller\AdminController::allChambres

app_select:
  path: /chambre/{id}
  controller: App\Controller\ChambreController::select
  requirements:
    id: '\d+'

app_admin_addChambre:
  path: /admin/addChambre
  controller: App\Controller\AdminController::addChambre

app_admin_updateChambre:
  path: /admin/updateChambre/{id}
  controller: App\Controller\AdminController::updateChambre
  requirements:
    id: '\d+'

app_admin_deleteChambre:
  path: /admin/deleteChambre/{id}
  controller: App\Controller\AdminController::deleteChambre
  requirements:
    id: '\d+'

app_admin_deletePhoto:
  path: /admin/deletePhoto/{id}
  controller: App\Controller\AdminController::deletePhoto
  requirements:
    id: '\d+'

app_book:
  path: /book
  controller: App\Controller\ReservationController::book
