controllers:
  resource: ../src/Controller/
  type: attribute

app_home:
  path: /
  controller: App\Controller\HomeController::home

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
